version: '3'

volumes:
  mongodb_local: {}

services:
  api:
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
      target: local
    container_name: api
    command: /start
    env_file: .env
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mongo:3.6.8
    container_name: database
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_local:/data/db

  mongo-seed:
    build:
      context: .
      dockerfile: ./compose/database/Dockerfile
    container_name: mongo-seed
    env_file: .env
    command: /mongo-seed/import.sh
    depends_on:
      - database
