version: '3'

volumes:
  mongodb_production: {}

services:
  api:
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
      target: production
    container_name: api
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./compose/database/Dockerfile
      target: production
    container_name: database
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_production:/data/db

  mongo-seed:
    build:
      context: .
      dockerfile: ./compose/database/Dockerfile
      target: production
    container_name: mongo-seed
    env_file: .env
    depends_on:
      - database

